### ISSUE TITLE
Problem while executing TestMail Api Call on localhost

### ISSUE THREAD

**Issue by saigkill** [EdiWang/Moonglade.Email#38]
While executing a Post Request to TestMail ApiCall a Error from Worker comes up:

For detailed output, run func with --verbose flag.
[2024-09-21T19:19:11.860Z] Host lock lease acquired by instance ID '00000000000000000000000015EAC718'.
[2024-09-21T19:22:27.587Z] Executing 'Functions.TestEmail' (Reason='This function was programmatically called via the host APIs.', Id=95131f9c-2e5c-4f91-82bb-c84addf628ac)
[2024-09-21T19:22:28.144Z] Function 'TestEmail', Invocation id '95131f9c-2e5c-4f91-82bb-c84addf628ac': An exception was thrown by the invocation.
[2024-09-21T19:22:28.146Z] Result: Function 'TestEmail', Invocation id '95131f9c-2e5c-4f91-82bb-c84addf628ac': An exception was thrown by the invocation.
Exception: System.InvalidOperationException:
[2024-09-21T19:22:28.147Z]
[2024-09-21T19:22:28.147Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FromBodyConversionFeature.ConvertAsync(FunctionContext context, Type targetType) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FromBodyConversionFeature.cs:line 91
[2024-09-21T19:22:28.148Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.Converters.FromBodyConverter.HandleResultAsync(ValueTask`1 result) in D:\a\_work\1\s\extensions\Worker.Extensions.Http\src\FromBodyConverter.cs:line 28
[2024-09-21T19:22:28.149Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.AwaitAndReturnConversionTaskResult(ValueTask`1 conversionTask) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 103
[2024-09-21T19:22:28.149Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 43
[2024-09-21T19:22:28.150Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.ConvertAsync(FunctionContext context, FunctionParameter parameter, IConverterContextFactory converterContextFactory, IInputConversionFeature inputConversionFeature, Object source) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 160
[2024-09-21T19:22:28.151Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 58
[2024-09-21T19:22:28.152Z]    at Moonglade.Function.Email.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\sasch\source\repos\Moonglade.Email\src\Moonglade.Function.Email\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-09-21T19:22:28.153Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-09-21T19:22:28.153Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-09-21T19:22:28.154Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91
Stack:    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FromBodyConversionFeature.ConvertAsync(FunctionContext context, Type targetType) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FromBodyConversionFeature.cs:line 91
[2024-09-21T19:22:28.154Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.Converters.FromBodyConverter.HandleResultAsync(ValueTask`1 result) in D:\a\_work\1\s\extensions\Worker.Extensions.Http\src\FromBodyConverter.cs:line 28
[2024-09-21T19:22:28.155Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.AwaitAndReturnConversionTaskResult(ValueTask`1 conversionTask) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 103
[2024-09-21T19:22:28.156Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 43
[2024-09-21T19:22:28.156Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.ConvertAsync(FunctionContext context, FunctionParameter parameter, IConverterContextFactory converterContextFactory, IInputConversionFeature inputConversionFeature, Object source) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 160
[2024-09-21T19:22:28.157Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 58
[2024-09-21T19:22:28.158Z]    at Moonglade.Function.Email.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\sasch\source\repos\Moonglade.Email\src\Moonglade.Function.Email\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-09-21T19:22:28.159Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-09-21T19:22:28.160Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-09-21T19:22:28.160Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91.
[2024-09-21T19:22:28.219Z] Executed 'Functions.TestEmail' (Failed, Id=95131f9c-2e5c-4f91-82bb-c84addf628ac, Duration=649ms)
[2024-09-21T19:22:28.220Z] System.Private.CoreLib: Exception while executing function: Functions.TestEmail. System.Private.CoreLib: Result: Failure
Exception: System.InvalidOperationException:
[2024-09-21T19:22:28.221Z]
[2024-09-21T19:22:28.221Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FromBodyConversionFeature.ConvertAsync(FunctionContext context, Type targetType) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FromBodyConversionFeature.cs:line 91
[2024-09-21T19:22:28.222Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.Converters.FromBodyConverter.HandleResultAsync(ValueTask`1 result) in D:\a\_work\1\s\extensions\Worker.Extensions.Http\src\FromBodyConverter.cs:line 28
[2024-09-21T19:22:28.223Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.AwaitAndReturnConversionTaskResult(ValueTask`1 conversionTask) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 103
[2024-09-21T19:22:28.223Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 43
[2024-09-21T19:22:28.224Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.ConvertAsync(FunctionContext context, FunctionParameter parameter, IConverterContextFactory converterContextFactory, IInputConversionFeature inputConversionFeature, Object source) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 160
[2024-09-21T19:22:28.225Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 58
[2024-09-21T19:22:28.226Z]    at Moonglade.Function.Email.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\sasch\source\repos\Moonglade.Email\src\Moonglade.Function.Email\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-09-21T19:22:28.228Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-09-21T19:22:28.228Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-09-21T19:22:28.229Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91
[2024-09-21T19:22:28.230Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FromBodyConversionFeature.ConvertAsync(FunctionContext context, Type targetType) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FromBodyConversionFeature.cs:line 91
[2024-09-21T19:22:28.230Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.Converters.FromBodyConverter.HandleResultAsync(ValueTask`1 result) in D:\a\_work\1\s\extensions\Worker.Extensions.Http\src\FromBodyConverter.cs:line 28
[2024-09-21T19:22:28.231Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.AwaitAndReturnConversionTaskResult(ValueTask`1 conversionTask) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 103
[2024-09-21T19:22:28.232Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 43
[2024-09-21T19:22:28.232Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.ConvertAsync(FunctionContext context, FunctionParameter parameter, IConverterContextFactory converterContextFactory, IInputConversionFeature inputConversionFeature, Object source) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 160
[2024-09-21T19:22:28.233Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 58
[2024-09-21T19:22:28.233Z]    at Moonglade.Function.Email.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\sasch\source\repos\Moonglade.Email\src\Moonglade.Function.Email\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-09-21T19:22:28.234Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-09-21T19:22:28.235Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
[2024-09-21T19:22:28.235Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91
[2024-09-21T19:22:28.236Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.

**Comment by saigkill** [comment]
I experimented a little bit. And tried the Request via Postman.

<img width="739" alt="image" src="https://github.com/user-attachments/assets/820dbc90-6ca3-4cca-8fa3-f34a68f564d4">

The app was deployed to moonglade-email453.azurewebsites.net with the deploy script. I tried to send the post request to /api/testmail.
Postman gives me a 404. Do i have to do anything after deploying the code and set the settings?

**Comment by EdiWang** [comment]
Please do not spend time on this project. Recently Microsoft made a change that will stop outlook.com personal accounts from working with my email library. I am planning to deprecate this project and move to Azure Communication Service by the end of this year.
